"""Add recruiter job postings

Revision ID: 1845ffc2508f
Revises: d605965b066c
Create Date: 2026-09-13 19:44:19.316850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1845ffc2508f'
down_revision = 'd605965b066c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'job_posting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recruiter_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('company', sa.String(length=150), nullable=False),
        sa.Column('location', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column(
            'employment_type',
            sa.String(length=20),
            server_default='full_time',
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.String(length=20),
            server_default='draft',
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "employment_type IN ("
            "'full_time', 'part_time', 'internship', 'contract')",
            name='ck_job_posting_employment_type',
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'open', 'closed')",
            name='ck_job_posting_status',
        ),
        sa.ForeignKeyConstraint(['recruiter_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_job_posting_recruiter_id'),
            ['recruiter_id'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posting_recruiter_id'))

    op.drop_table('job_posting')
    # ### end Alembic commands ###
