"""Add recruiter access requests

Revision ID: 1bb51005723c
Revises: 8107f343c36a
Create Date: 2026-09-16 14:43:03.281310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb51005723c'
down_revision = '8107f343c36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recruiter_access_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(length=150), nullable=False),
        sa.Column('company_website', sa.String(length=500), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.String(length=20),
            server_default='pending',
            nullable=False,
        ),
        sa.Column('submitted_at', sa.DateTime(), nullable=False),
        sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('review_note', sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(status = 'pending' AND reviewed_by_id IS NULL "
            "AND reviewed_at IS NULL) "
            "OR (status IN ('approved', 'rejected') "
            "AND reviewed_by_id IS NOT NULL "
            "AND reviewed_at IS NOT NULL)",
            name='ck_recruiter_access_request_review',
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name='ck_recruiter_access_request_status',
        ),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', name='uq_recruiter_access_request_user_id'
        )
    )
    with op.batch_alter_table(
        'recruiter_access_request', schema=None
    ) as batch_op:
        batch_op.create_index(
            'ix_recruiter_access_request_status_submitted',
            ['status', 'submitted_at'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'recruiter_access_request', schema=None
    ) as batch_op:
        batch_op.drop_index('ix_recruiter_access_request_status_submitted')

    op.drop_table('recruiter_access_request')
    # ### end Alembic commands ###
