"""Add user notifications

Revision ID: 338f62cc0bb8
Revises: 1bb51005723c
Create Date: 2026-09-16 17:45:32.938013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338f62cc0bb8'
down_revision = '1bb51005723c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'notification',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(length=40), nullable=False),
        sa.Column('title', sa.String(length=160), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('application_status', 'recruiter_access')",
            name='ck_notification_kind',
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(
            'ix_notification_user_created',
            ['user_id', 'created_at'],
            unique=False,
        )
        batch_op.create_index(
            'ix_notification_user_read', ['user_id', 'read_at'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_read')
        batch_op.drop_index('ix_notification_user_created')

    op.drop_table('notification')
    # ### end Alembic commands ###
