"""Add application scoring records

Revision ID: 7d4c3f4c4f31
Revises: 804002a4f4e5
Create Date: 2026-09-14 22:40:23.029642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4c3f4c4f31'
down_revision = '804002a4f4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'application_score',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=False),
        sa.Column('scored_by_id', sa.Integer(), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=False),
        sa.Column('score_breakdown', sa.JSON(), nullable=False),
        sa.Column('weights', sa.JSON(), nullable=False),
        sa.Column('matching_skills', sa.JSON(), nullable=False),
        sa.Column('missing_skills', sa.JSON(), nullable=False),
        sa.Column('explanations', sa.JSON(), nullable=False),
        sa.Column('scoring_version', sa.String(length=50), nullable=False),
        sa.Column('scored_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            'overall_score >= 0 AND overall_score <= 100',
            name='ck_application_score_range',
        ),
        sa.ForeignKeyConstraint(['application_id'], ['job_application.id'], ),
        sa.ForeignKeyConstraint(['scored_by_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('application_id')
    )
    with op.batch_alter_table('application_score', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_application_score_scored_by_id'),
            ['scored_by_id'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_score_scored_by_id'))

    op.drop_table('application_score')
    # ### end Alembic commands ###
