"""Add candidate job applications

Revision ID: 804002a4f4e5
Revises: 1845ffc2508f
Create Date: 2026-09-14 13:19:16.379258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804002a4f4e5'
down_revision = '1845ffc2508f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'job_application',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('resume_filename', sa.String(length=255), nullable=False),
        sa.Column('resume_content', sa.LargeBinary(), nullable=False),
        sa.Column('resume_text', sa.Text(), nullable=False),
        sa.Column('job_title_snapshot', sa.String(length=150), nullable=False),
        sa.Column('job_description_snapshot', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.String(length=20),
            server_default='submitted',
            nullable=False,
        ),
        sa.Column('submitted_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ("
            "'submitted', 'under_review', 'shortlisted', "
            "'rejected', 'hired', 'withdrawn')",
            name='ck_job_application_status',
        ),
        sa.ForeignKeyConstraint(['candidate_id'], ['user.id']),
        sa.ForeignKeyConstraint(['job_id'], ['job_posting.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'candidate_id',
            'job_id',
            name='uq_job_application_candidate_job',
        ),
    )
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_job_application_candidate_id'),
            ['candidate_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_job_application_job_id'),
            ['job_id'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_application_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_application_candidate_id'))

    op.drop_table('job_application')
    # ### end Alembic commands ###
