"""Add candidate profiles

Revision ID: 8107f343c36a
Revises: 7d4c3f4c4f31
Create Date: 2026-09-15 22:49:36.752226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8107f343c36a'
down_revision = '7d4c3f4c4f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candidate_profile',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('headline', sa.String(length=150), nullable=False),
        sa.Column('bio', sa.Text(), nullable=False),
        sa.Column('location', sa.String(length=150), nullable=False),
        sa.Column('skills', sa.Text(), nullable=False),
        sa.Column('education', sa.String(length=255), nullable=False),
        sa.Column('graduation_year', sa.Integer(), nullable=True),
        sa.Column('github_url', sa.String(length=500), nullable=False),
        sa.Column('linkedin_url', sa.String(length=500), nullable=False),
        sa.Column('portfolio_url', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            'graduation_year IS NULL OR '
            '(graduation_year >= 1900 AND graduation_year <= 2100)',
            name='ck_candidate_profile_graduation_year',
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='uq_candidate_profile_user_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_profile')
    # ### end Alembic commands ###
