"""Baseline existing resume screener tables

Revision ID: adca466b46ae
Revises: 
Create Date: 2026-09-13 12:29:49.489288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adca466b46ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=150), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_user_email'), ['email'], unique=True
        )

    op.create_table(
        'analysis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('resume_filename', sa.String(length=255), nullable=False),
        sa.Column('analysis_type', sa.String(length=50), nullable=False),
        sa.Column('job_description', sa.Text(), nullable=False),
        sa.Column('match_score', sa.Integer(), nullable=False),
        sa.Column('detected_skills', sa.Text(), nullable=False),
        sa.Column('matching_skills', sa.Text(), nullable=False),
        sa.Column('missing_skills', sa.Text(), nullable=False),
        sa.Column('candidate_rank', sa.Integer(), nullable=True),
        sa.Column('interview_questions', sa.Text(), nullable=False),
        sa.Column('score_breakdown', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_analysis_user_id'), ['user_id'], unique=False
        )

    op.create_table(
        'scoring_preference',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('weights', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_preference', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_scoring_preference_user_id'),
            ['user_id'],
            unique=True
        )

    op.create_table(
        'analysis_context',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('resume_text', sa.Text(), nullable=False),
        sa.Column('explanations', sa.Text(), nullable=False),
        sa.Column('weights', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['analysis_id'], ['analysis.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_context', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_analysis_context_analysis_id'),
            ['analysis_id'],
            unique=True
        )
        batch_op.create_index(
            batch_op.f('ix_analysis_context_user_id'),
            ['user_id'],
            unique=False
        )

    op.create_table(
        'resume_rewrite',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('tone', sa.String(length=30), nullable=False),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('rewritten_text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['analysis_id'], ['analysis.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_rewrite', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_resume_rewrite_analysis_id'),
            ['analysis_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_resume_rewrite_user_id'),
            ['user_id'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_rewrite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_rewrite_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_rewrite_analysis_id'))

    op.drop_table('resume_rewrite')
    with op.batch_alter_table('analysis_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_context_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_context_analysis_id'))

    op.drop_table('analysis_context')
    with op.batch_alter_table('scoring_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_preference_user_id'))

    op.drop_table('scoring_preference')
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_user_id'))

    op.drop_table('analysis')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
